### ISSUE TITLE
Porte 80 e 443 esterne

### ISSUE THREAD

**Issue by andreanilorenzo** [andrea-mattioli/ha_reverse_proxy_docker#1]
E' possibile modificare la porta 443 esterna con un'altra porta:

Nel mio setup la porta 443 sulla rete esterna è già impegnata per un altro server.

**Comment by andrea-mattioli** [comment]
basta modificare la porta sul configuration dove vedi host 443 metti una porta diversa che poi sarà quella che userai per contattare HA dall'esterno.
