### ISSUE TITLE
addon non si avvia / installa

### ISSUE THREAD

**Issue by runnerluca87** [andrea-mattioli/ha_reverse_proxy_docker#3]
Dopo Aggiornamento alla release 2022.3.6 addon non si avvia e non si re-installa, restituendo questo errore  

 Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by andrea-mattioli** [comment]
Non mi risultano problemi di build dell'addon o altro su questa versione, Client Timeout penso che dipenda dalla tua connettività.

**Comment by runnerluca87** [comment]
In realtà abbiamo questo problema su 4-5 installazioni diverse, da qualche prova che sto facendo forse ci sono problema di raggiungibilità dei server ospitati da aws tipo duckdns
